port:
  bus:
    channel: "can-bb"
    interface: "socketcan"
    receive_timeout: 0.001
  process_interval: 0.001
  device_connect_interval: 0.1
message_types:
- key: "node_info"
  dbc_name: "NODE_INFO"
  priority: 6
  pgn: 65280  # 0xFF00
  direction: "rx"
  signals:
  - key: "node_type"
    dbc_name: "NODE_TYPE"
    start_bit: 0
    signal_size: 7
    c_type: "uint8_t"
    py_type: "int"
  - key: "node_id"
    dbc_name: "NODE_ID"
    start_bit: 7
    signal_size: 7
    c_type: "uint8_t"
    py_type: "int"
  - key: "version_major"
    dbc_name: "VERSION_MAJOR"
    start_bit: 14
    signal_size: 6
    c_type: "uint8_t"
    py_type: "int"
  - key: "version_minor"
    dbc_name: "VERSION_MINOR"
    start_bit: 20
    signal_size: 6
    c_type: "uint8_t"
    py_type: "int"
  - key: "version_patch"
    dbc_name: "VERSION_PATCH"
    start_bit: 26
    signal_size: 6
    c_type: "uint8_t"
    py_type: "int"
  - key: "uptime"
    dbc_name: "UPTIME"
    start_bit: 32
    signal_size: 32
    unit: "s"
    c_type: "uint32_t"
    py_type: "int"
- key: "therm_state"
  dbc_name: "THERM_STATE"
  priority: 6
  pgn: 65296  # 0xFF10
  direction: "rx"
  signals:
  - key: "temp_c"
    dbc_name: "TEMP_C"
    start_bit: 0
    signal_size: 16
    signed: true
    value_scale: 0.01
    unit: "C"
    c_type: "double"
    py_type: "float"
  - key: "temp_v"
    dbc_name: "TEMP_V"
    start_bit: 16
    signal_size: 16
    value_scale: 0.001
    unit: "V"
    c_type: "double"
    py_type: "float"
- key: "relay_state"
  dbc_name: "RELAY_STATE"
  priority: 6
  pgn: 65297  # 0xFF11
  direction: "rx"
  signals:
  - key: "on"
    dbc_name: "RELAY_STATE"
    start_bit: 0
    signal_size: 1
    c_type: "uint8_t"
    py_type: "flag"
- key: "relay_cmd"
  dbc_name: "RELAY_CMD"
  priority: 6
  pgn: 4096  # 0x1000
  direction: "tx"
  signals:
  - key: "on"
    dbc_name: "RELAY_STATE"
    start_bit: 0
    signal_size: 1
    c_type: "uint8_t"
    py_type: "flag"
node_types:
- key: "master"
  messages: []
  node_state_class: "brewbot.can.node_state:MasterNodeState"
- key: "thermometer"
  messages:
  - key: "node_info"
    msg_type_ref: "node_info"
    direction: "rx"
  - key: "therm_state"
    msg_type_ref: "therm_state"
    direction: "rx"
  node_state_class: "brewbot.can.node_state:ThermometerNodeState"
  mock_class: "brewbot.can.mock:MockThermometer"
- key: "relay"
  messages:
  - key: "node_info"
    msg_type_ref: "node_info"
  - key: "relay_state"
    msg_type_ref: "relay_state"
  - key: "relay_cmd"
    msg_type_ref: "relay_cmd"
    frequency: 2.0 # msg / s
  node_state_class: "brewbot.can.node_state:RelayNodeState"
  mock_class: "brewbot.can.mock:MockRelay"
nodes:
- key: "master"
  node_type_ref: "master"
  node_addr: 16  # 0x10
  debug: {}
- key: "therm_01"
  node_type_ref: "thermometer"
  node_addr: 112 # 0x70
  params:
    window: 10.0 # s
  debug:
    mock: false
- key: "therm_02"
  node_type_ref: "thermometer"
  node_addr: 113 # 0x71
  params:
    window: 10.0 # s
  debug:
    mock: false
- key: "motor_01"
  node_type_ref: "relay"
  node_addr: 128 # 0x80
  debug:
    mock: false
- key: "heat_01"
  node_type_ref: "relay"
  node_addr: 129 # 0x81
  debug:
    mock: false
assembly_types:
- key: "kettle"
  assembly_class: "brewbot.assembly.kettle:KettleAssembly"
assemblies:
- key: "kettle_1"
  assembly_type_ref: "kettle"
  nodes:
    thermometer:
    - "therm_01"
    - "therm_02"
    motor: "motor_01"
    heat_plate: "heat_01"
  params:
    - name: volume
      value: 30.0 # l
    - name: controller
      config_class: "brewbot.config:ControllerConfig"
      value:
        p_gain: 1.0
        d_gain: 50.0
        max_cs: 3.5
        pwm_interval: 0.2  # times per second
        low_jump_thres: 0.2
        high_jump_thres: 0.8
    - name: data_collect
      config_class: "brewbot.config:DataCollectConfig"
      value:
        window: 30.0
        collect_interval: 2.0 # times per second
